services:
  sla-mysql:
    container_name: sla-mysql
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  sla_app:
    image: sla_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sla-mysql
    environment:
      DATABASE_HOST: sla-mysql