services:
  sla-mysql:
    hostname: sla-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3307:3306'
    networks:
      - iris

  oncall-mysql:
    hostname: oncall-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - iris

networks:
  iris: